apiVersion: v1
kind: Pod
spec:
    containers:
        - name: omri-flask-app
          image: ezezeasy/ez-docker-helm-build
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: Always
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
    volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
